### ISSUE TITLE
Any ideas to try and update this?

### ISSUE THREAD

**Issue by wgaylord** [CXgamer/MCsim#1]

**Comment by Breina** [comment]
The main reason this wasn't maintained was because the reflection mappings took a long time and I had to redo a lot of manual stuff every update.

I've had a quick look, and all of the mappings seem to be included with minecraft itself, which would make maintaining this project a whole lot easier.

Got other projects running at the moment; might at some point resume with this. No promises though.

**Comment by wgaylord** [comment]
Surprisingly I don't remember even making this issue.  And I totally understand that mapping issue. (I use to make my own snapshot mappings before mojang started releasing them)

I am going to just close tho. Since I really don't remember opening it in the first place.
